const express = require('express')
const { verifyToken, verifyTokenCustomer } = require('../../middlewares')
const auth = require('../../modules/auth')
const adminMenu = require('../../modules/admin_menu')
const roles = require('../../modules/roles')
const locations = require('../../modules/locations')
const users = require('../../modules/users')
const publicApi = require('../../modules/public');
const dashboard = require('../../modules/dashboard')
const banner = require('../../modules/banner')
const newsCategory = require('../../modules/news_category')
const news = require('../../modules/news')
const contactUsAdmin = require('../../modules/contact_us_admin')
const contactUsUser = require('../../modules/contact_us_user')
const departement = require('../../modules/departement')
const jobCareer = require('../../modules/job_career')
const locationArea = require('../../modules/location_area')
const maritalStatus = require('../../modules/marital_status')
const religion = require('../../modules/religion')
const province = require('../../modules/province')
const city = require('../../modules/city')
const degree = require('../../modules/degree')
const careerApply = require('../../modules/career_apply')
const member = require('../../modules/member')
const publicBanner = require('../../modules/public_banner')
const typeProduct = require('../../modules/type_product')
const publicTypeProduct = require('../../modules/public_type_product')
const product = require('../../modules/product')
const publicProduct = require('../../modules/public_product')
const flayerProduct = require('../../modules/flayer_product')
const featureProduct = require('../../modules/feature_product')
const featureChildProduct = require('../../modules/feature_child_product')
const galleryProduct = require('../../modules/gallery_product')
const product360 = require('../../modules/360_product')
const publicFlayerProduct = require('../../modules/public_flayer_product')
const publicFeatureProduct = require('../../modules/public_feature_product')
const publicArticleCategory = require('../../modules/public_article_category')
const publicArticle = require('../../modules/public_article')
const customer = require('../../modules/customer')
const voucher = require('../../modules/voucher')
const downloadFlayerProduct = require('../../modules/download_flayer_product')
const consultation = require('../../modules/consultation')
const memberVoucher = require('../../modules/member_voucher')
const publicMemberVoucher = require('../../modules/public_member_voucher')
const publicVoucher = require('../../modules/public_voucher')
const specificationProduct = require('../../modules/specification_product')

const routing = express();
const API_TAG = '/api/v1';
/* RULE
naming convention endpoint: using plural
*/
// public api register here
routing.use(`${API_TAG}/auth`, auth)
routing.use(`${API_TAG}/public/api`, publicApi)
routing.use(`${API_TAG}/public/banner`, publicBanner)
routing.use(`${API_TAG}/public/type-product`, publicTypeProduct)
routing.use(`${API_TAG}/public/product`, publicProduct)
routing.use(`${API_TAG}/contact-us-user`, contactUsUser)
routing.use(`${API_TAG}/public/contact-us-user`, contactUsUser)
routing.use(`${API_TAG}/public/flayer-product`, publicFlayerProduct)
routing.use(`${API_TAG}/public/feature-product`, publicFeatureProduct)
routing.use(`${API_TAG}/public/article-category`, publicArticleCategory)
routing.use(`${API_TAG}/public/article`, publicArticle)
routing.use(`${API_TAG}/download-flayer-product`, downloadFlayerProduct)
routing.use(`${API_TAG}/public/download-flayer-product`, downloadFlayerProduct)
routing.use(`${API_TAG}/consultation`, consultation)
routing.use(`${API_TAG}/public/consultation`, consultation)
routing.use(`${API_TAG}/public/member-voucher`, verifyTokenCustomer, publicMemberVoucher)
routing.use(`${API_TAG}/public/voucher`, verifyTokenCustomer, publicVoucher)

// need token verify register here
routing.use(`${API_TAG}/admin-menu`, verifyToken, adminMenu)
routing.use(`${API_TAG}/roles`, verifyToken, roles)
routing.use(`${API_TAG}/locations`, verifyToken, locations)
routing.use(`${API_TAG}/users`, verifyToken, users)
routing.use(`${API_TAG}/dashboard`, verifyToken, dashboard)
routing.use(`${API_TAG}/banner`, verifyToken, banner)
routing.use(`${API_TAG}/news-category`, verifyToken, newsCategory)
routing.use(`${API_TAG}/news`, verifyToken, news)
routing.use(`${API_TAG}/contact-us-admin`, verifyToken, contactUsAdmin)
routing.use(`${API_TAG}/departement`, verifyToken, departement)
routing.use(`${API_TAG}/job-career`, verifyToken, jobCareer)
routing.use(`${API_TAG}/location-area`, verifyToken, locationArea)
routing.use(`${API_TAG}/marital-status`, verifyToken, maritalStatus)
routing.use(`${API_TAG}/religion`, verifyToken, religion)
routing.use(`${API_TAG}/province`, verifyToken, province)
routing.use(`${API_TAG}/city`, verifyToken, city)
routing.use(`${API_TAG}/degree`, verifyToken, degree)
routing.use(`${API_TAG}/career-apply`, verifyToken, careerApply)
routing.use(`${API_TAG}/member`, verifyToken, member)
routing.use(`${API_TAG}/type-product`, verifyToken, typeProduct)
routing.use(`${API_TAG}/product`, verifyToken, product)
routing.use(`${API_TAG}/flayer-product`, verifyToken, flayerProduct)
routing.use(`${API_TAG}/feature-product`, verifyToken, featureProduct)
routing.use(`${API_TAG}/feature-child-product`, verifyToken, featureChildProduct)
routing.use(`${API_TAG}/gallery-product`, verifyToken, galleryProduct)
routing.use(`${API_TAG}/product-360`, verifyToken, product360)
routing.use(`${API_TAG}/customer`, verifyToken, customer)
routing.use(`${API_TAG}/voucher`, verifyToken, voucher)
routing.use(`${API_TAG}/member-voucher`, verifyToken, memberVoucher)
routing.use(`${API_TAG}/specification-product`, verifyToken, specificationProduct)
module.exports = routing;
