/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('mst_permissions').del()
  await knex('mst_permissions').insert([
    {
      id: '1',
      name: 'read',
      created_at: '2022-08-02 12:12:59.001 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '2',
      name: 'create',
      created_at: '2022-08-02 12:12:59.043 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '3',
      name: 'update',
      created_at: '2022-08-02 12:12:59.093 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '4',
      name: 'delete',
      created_at: '2022-08-02 12:12:59.143 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '5',
      name: 'export',
      created_at: '2022-08-02 13:04:17.775 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '11',
      name: 'blokir',
      created_at: '2022-08-19 11:01:20.996 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '12',
      name: 'preview',
      created_at: '2022-10-05 17:05:21.401 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '13',
      name: 'upload',
      created_at: '2022-10-05 17:05:56.810 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '14',
      name: 'continue',
      created_at: '2022-10-05 17:06:22.680 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '15',
      name: 'download',
      created_at: '2022-10-06 09:51:54.780 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '16',
      name: 'cetak_serah_terima_dokumen',
      created_at: '2022-10-06 09:51:54.900 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '17',
      name: 'cetak_serah_terima_stnk',
      created_at: '2022-10-06 09:51:54.965 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '18',
      name: 'email',
      created_at: '2022-10-06 10:07:29.709 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '8',
      name: 'edit_dokumen',
      created_at: '2022-10-12 16:30:00.187 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '7',
      name: 'batal_titip',
      created_at: '2022-10-12 16:29:02.919 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '9',
      name: 'reset_password',
      created_at: '2022-10-13 08:14:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null
    },
    {
      id: '19',
      name: 'verifikasi',
      created_at: '2022-10-26 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '20',
      name: 'edit_dokumen_unit_terjual_rilis',
      created_at: '2022-11-04 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '21',
      name: 'edit_unit_terjual_rilis',
      created_at: '2022-11-04 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '22',
      name: 'change_monitoring',
      created_at: '2022-11-04 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '23',
      name: 'inspeksi_ulang',
      created_at: '2022-11-04 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '24',
      name: 'ubah_hasil_inspeksi',
      created_at: '2022-11-04 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '25',
      name: 'ubah_dokumen',
      created_at: '2023-01-23 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '26',
      name: 'ubah_inventori',
      created_at: '2023-01-23 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '27',
      name: 'history',
      created_at: '2023-01-23 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '28',
      name: 'cetak_serah_terima_unit',
      created_at: '2023-01-23 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '29',
      name: 'cetak_serah_keluar_unit',
      created_at: '2023-01-23 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '30',
      name: 'tambah_resi',
      created_at: '2023-01-23 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '31',
      name: 'ubah_tanggal_ bpkb',
      created_at: '2023-01-23 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '32',
      name: 'unggah_bpkb',
      created_at: '2023-01-23 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '33',
      name: 'unduh_bpkb',
      created_at: '2023-01-23 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '34',
      name: 'unggah_massal',
      created_at: '2023-01-23 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '35',
      name: 'aktivasi_midtrans',
      created_at: '2023-01-23 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '36',
      name: 'cetak_skpl',
      created_at: '2023-01-23 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '37',
      name: 'privilege',
      created_at: '2023-01-23 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    },
    {
      id: '39',
      name: 'ubah_status',
      created_at: '2023-01-23 12:29:23.759 +0700',
      created_by: null,
      updated_at: null,
      updated_by: null,
      deleted_at: null,
      deleted_by: null,
    }
  ]);
};
