require('dotenv').config();

module.exports = {
  LIMIT: 10,
  PAGE: 1,
  SQL: {
    SORT: ['ASC', 'DESC']
  },
  HTTP: {
    CREATED: 201,
    OK: 200,
    ACCEPTED: 202,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500
  },
  VEHICLE_CODE: [
    { code: 'C', name: 'car' },
    { code: 'B', name: 'bike' }
  ],
  VEHICLE_TYPE: {
    CAR: 'car',
    BIKE: 'bike',
    CAR_AND_BIKE: 'car and bike'
  },
  ROLE: {
    ADMIN: 'Administrator',
    CUSTOMER_BUYER: 'Customer-Buyer',
    CLIENT_SELLER: 'Client-Seller',
    ONLY_CONDUCTOR: ['Coordinator', 'Admin Office', 'Branch Head', 'Conductor', 'Auction Officer'],
    ONLY_INSPECTION: ['Inspection', 'Inspector'],
    AUCTION: ['Coordinator', 'Admin Office', 'Branch Head', 'Conductor', 'Customer-Buyer', 'Auction Officer'],
    AUCTION_OFFICER: 'Auction Officer'
  },
  VEHICLE_TYPE_ENUM: ['car', 'bike', 'car and bike'],
  MORGAN_FORMAT: {
    DEV: '[:date[clf]] :remote-addr :remote-user \x1b[36m:method \x1b[36m:url \x1b[33m:status \x1b[32m:response-time\x1b[36m(ms)\x1b[0m',
    PROD: '[:date[clf]] :remote-addr :remote-user :method :url :status :response-time(ms)'
  },
  MOBILIZATION_CATEGORY: [
    { id: 1, name: 'Ekspedisi', type: 'car & bike' },
    { id: 2, name: 'Pickup', type: 'car & bike' },
    { id: 3, name: 'Non-Pickup', type: 'car & bike' },
  ],
  VEHICLE_CATEGORY: [
    { id: 1, name: 'Penumpang' },
    { id: 2, name: 'Komersial' },
    { id: 3, name: 'Pertambangan' },
    { id: 4, name: 'Lainnya' },
  ],
  INV_STATUS: {
    TERSEDIA: '1c82d8ac-91f5-4643-8c57-7d5827c68d19',
    TERJUAL: '4b4a1546-6a0a-4c86-b2ab-1cce303d0542'
  },
  MODEL_PROPERTIES: {
    TABLES: {
      JENIS_AKUN: 'mst_jenis_akun',
      AKUN: 'mst_akun',
      METODE_PEMBAYARAN: 'mst_metode_pembayaran',
      PAJAK_DISKON: 'mst_pajak_diskon',
      CUSTOMERS_SUPPLIERS: 'mst_customers_suppliers',
      TRSPENJUALAN: 'trs_penjualan',
      TRSPEMBELIAN: 'trs_pembelian',
      TRSPENJUALAN_DETAIL: 'trs_penjualan_detail',
      TRSPEMBELIAN_DETAIL: 'trs_pembelian_detail',
      TRSPENJUALAN_PAYMENT: 'trs_penjualan_payment',
      TRSPEMBELIAN_PAYMENT: 'trs_pembelian_payment',
      TRSPENJUALAN_PAYMENT_DETAIL: 'trs_penjualan_payment_detail',
      TRSPEMBELIAN_PAYMENT_DETAIL: 'trs_pembelian_payment_detail',
      KAS_MASUK: 'trs_kas_masuk',
      KAS_KELUAR: 'trs_kas_keluar',
      SUMBER_PENERIMAAN: 'mst_sumber_pemasukan',
      TUJUAN_PENGELUARAN: 'mst_tujuan_pengeluaran',
      KATEGORI_KAS: 'mst_kategori_kas',
      KATEGORI_JURNAL: 'mst_kategori_jurnal',
      JURNAL_UMUM: 'trs_jurnal_umum',
      BANK: 'mst_bank',
      INVENTORY: 'inv_car_stock',
      TRANSPORTATION_TYPE: 'mst_transportation_type',
      BRAND: 'mst_brand',
      GROUP_TYPE: 'mst_group_type',
      TYPE: 'mst_type',
      LOCATION: 'mst_location',
      POOL: 'mst_pool',
      CLIENT: 'mst_client',
      CLIENT_TYPE: 'mst_client_type',
      COLOR: 'mst_color',
      INVENTORY_IMAGE: 'inv_car_image',
      STATUS_INVENTORY: 'mst_status_inventory',
      WITHDRAWAL: 'inv_car_unit_withdrawal',
      BIKE_INVENTORY: 'inv_bike_stock',
      CAR_INVENTORY_DOCUMENT: 'inv_car_document',
      BIKE_INVENTORY_IMAGE: 'inv_bike_image',
      BIKE_INVENTORY_DOCUMENT: 'inv_bike_document',
      BIKE_WITHDRAWAL: 'inv_bike_unit_withdrawal',
      AUCTION: 'auc_auction',
      AUCTION_PROCEDURE: 'web_auction_procedure',
      CAR_ALLOCATION: 'auc_car_allocation',
      CAR_ALLOCATION_DETAIL: 'auc_car_allocation_detail',
      BIKE_ALLOCATION: 'auc_bike_allocation',
      BIKE_ALLOCATION_DETAIL: 'auc_bike_allocation_detail',
      AUCTION_RESULT_CAR: 'auc_result_auction_car',
      AUCTION_RESULT_BIKE: 'auc_result_auction_bike',
      AUCTION_CAR_HISTORY: 'auc_car_history',
      AUCTION_BIKE_HISTORY: 'auc_bike_history',
      BIDDER: 'auc_customer_bidder',
      NIPL: 'auc_customer_nipl',
      DEPOSIT: 'auc_customer_deposit',
      CUSTOMER: 'mst_customer',
      PAYMENT_CAR: 'payment_car',
      PAYMENT_BIKE: 'payment_bike',
      PAYMENT_CAR_PROOF: 'payment_car_proof',
      PAYMENT_BIKE_PROOF: 'payment_bike_proof',
      NOTIFICATION: 'mst_notification_lelang',
      FEE_SETTING: 'mst_fee_setting',
      SELL_IT: 'mst_titip_jual',
      USER: 'mst_users',
      LOG_BID: 'log_bid',
      LOG_BID_REPORT: 'log_bid_report',
      AUCTION_RESULT_INVOICE: 'auc_result_auction_invoice',
      MIDTRANS: 'midtrans_payment',
      CORRECTION_MONITORING_USER: 'correction_monitoring_user',
      TRANSFER: 'transfer_payment',
      VW_INV_CAR: 'invoice_client_car',
      VW_INV_BIKE: 'invoice_client_bike',
      VW_INFO_BIDDER: 'info_bidder',
      WEB_SELL_IT: 'web_sell_it',
      INFO_BIDDER: 'info_bidder',
      INSPECTION_HISTORY: 'inspection_history',
      WEB_SETTING: 'web_setting',
      VW_BATAL_TITIP_CAR: 'batal_titip_queue_car',
      VW_BATAL_TITIP_BIKE: 'batal_titip_queue_bike',
      MST_TITIP_JUAL: 'mst_titip_jual',
      WEB_ARTICLE: 'web_article',
      WEB_ARTICLE_CATEGORY: 'web_article_categories',
      ROLE: 'mst_role',
      PAYMENT_CANCELED_HISTORY: 'payment_canceled',
      DEBITUR: 'mst_debitur',
      AUCTION_RESULT_INVOICE_DEBITUR: 'auc_result_auction_invoice_debitur',
      PPN: 'mst_ppn',
      ADDITIONAL_FEE: 'mst_additional_cost',
      OTHER_FEES: 'mst_additional_cost',
      INVOICE_CONFIG: 'mst_invoice_config',
      PUBLISH_CATALOG_LOG: 'publish_catalog_log',
      ADMIN_FEE_SETTING: 'mst_admin_fee_setting',
      NEWS_CATEGORY: 'mst_news_category',
      NEWS: 'mst_news',
      CONTACT_US_ADMIN: 'mst_contact_us_admin',
      CONTACT_US_USER: 'mst_contact_us_user',
      DEPARTEMENT: 'mst_departement',
      JOB_CAREER: 'mst_job_career',
      LOCATION_AREA: 'mst_location_area',
      MARITAL_STATUS: 'mst_marital_status',
      RELIGION: 'mst_religion',
      DEGREE: 'mst_degree',
      PROVINCE: 'mst_province',
      CITY: 'mst_city',
      CAREER_APPLY: 'mst_career_apply',
      MEMBER: 'mst_member',
      TYPE_PRODUCT: 'mst_type_product',
      PRODUCT: 'mst_product',
      FLYER_PRODUCT: 'mst_flayer_product',
      FEATURE_PRODUCT: 'mst_feature_product',
      FEATURE_CHILD_PRODUCT: 'mst_feature_child_product',
      GALLERY_PRODUCT: 'mst_gallery_product',
      PRODUCT_360: 'mst_360_product',
      VOUCHER: 'mst_voucher',
      DATA_DOWNLOAD_FLYER_PRODUK: 'data_download_flayer_produk',
      CONSULTATION: 'mst_consultation',
      MEMBER_VOUCHER: 'member_vouchers',
      SPECIFICATION_PRODUCT: 'mst_specification_product',
      SPECIFICATION_LABEL: 'mst_specification_label',
      SPECIFICATION_VALUE: 'mst_specification_value',
      PRODUCT_MODEL: 'mst_product_model',
      PRODUCT_DIMENSI: 'mst_product_dimensi',
      REVIEW: 'mst_review',
      CAMPAIGN_PARTICIPANT: 'mst_campaign_participant',
      EMAIL_EMPLOYEE: 'mst_email_employee'
    },
    PRIMARY_KEY: {
      JENIS_AKUN: 'jenis_akun_id',
      AKUN: 'akun_id',
      METODE_PEMBAYARAN: 'metode_pembayaran_id',
      PAJAK_DISKON: 'pajak_diskon_id',
      CUSTOMERS_SUPPLIERS: 'customers_suppliers_id',
      SUMBER_PENERIMAAN: 'sumber_pemasukan_id',
      KATEGORI_KAS: 'kategori_kas_id',
      TRSPENJUALAN: 'trs_penjualan_id',
      TRSPEMBELIAN: 'trs_pembelian_id',
      TRSPENJUALAN_DETAIL: 'trs_penjualan_detail_id',
      TRSPEMBELIAN_DETAIL: 'trs_pembelian_detail_id',
      TRSPENJUALAN_PAYMENT: 'trs_penjualan_payment_id',
      TRSPEMBELIAN_PAYMENT: 'trs_pembelian_payment_id',
      TRSPENJUALAN_PAYMENT_DETAIL: 'trs_penjualan_payment_detail_id',
      TRSPEMBELIAN_PAYMENT_DETAIL: 'trs_pembelian_payment_detail_id',
      KAS_MASUK: 'kas_masuk_id',
      KAS_KELUAR: 'kas_keluar_id',
      TUJUAN_PENGELUARAN: 'tujuan_pengeluaran_id',
      KATEGORI_JURNAL: 'kategori_jurnal_id',
      JURNAL_UMUM: 'jurnal_umum_id',
      BANK: 'id',
      INVENTORY: 'inventory_car_id',
      TRANSPORTATION_TYPE: 'transportation_id',
      BRAND: 'brand_id',
      GROUP_TYPE: 'group_type_id',
      TYPE: 'type_id',
      LOCATION: 'location_id',
      BANNER: 'banner_id',
      POOL: 'pool_id',
      CLIENT: 'client_id',
      CLIENT_TYPE: 'client_type_id',
      COLOR: 'id',
      INVENTORY_IMAGE: 'car_inventory_image_id',
      STATUS_INVENTORY: 'status_inventory_id',
      WITHDRAWAL: 'car_withdrawal_id',
      BIKE_INVENTORY: 'inventory_bike_id',
      CAR_INVENTORY_DOCUMENT: 'car_document_id',
      BIKE_INVENTORY_IMAGE: 'bike_inventory_image_id',
      BIKE_INVENTORY_DOCUMENT: 'bike_document_id',
      BIKE_WITHDRAWAL: 'bike_withdrawal_id',
      AUCTION: 'auction_id',
      CAR_ALLOCATION: 'car_allocation_id',
      CAR_ALLOCATION_DETAIL: 'car_allocation_detail_id',
      BIKE_ALLOCATION: 'bike_allocation_id',
      BIKE_ALLOCATION_DETAIL: 'bike_allocation_detail_id',
      AUCTION_RESULT_CAR: 'auction_car_id',
      AUCTION_RESULT_BIKE: 'auction_bike_id',
      AUCTION_CAR_HISTORY: 'car_history_id',
      AUCTION_BIKE_HISTORY: 'bike_history_id',
      BIDDER: 'bidder_id',
      NIPL: 'nipl_id',
      DEPOSIT: 'deposit_id',
      CUSTOMER: 'customer_id',
      PAYMENT_CAR: 'payment_car_id',
      PAYMENT_BIKE: 'payment_bike_id',
      PAYMENT_CAR_PROOF: 'payment_car_proof_id',
      PAYMENT_BIKE_PROOF: 'payment_bike_proof_id',
      NOTIFICATION: 'notification_id',
      FEE_SETTING: 'fee_setting_id',
      USER: 'users_id',
      LOG_BID: 'log_id',
      LOG_BID_REPORT: 'log_id',
      AUCTION_RESULT_INVOICE: 'result_auction_invoice_id',
      MIDTRANS: 'midtrans_payment_id',
      WEB_SELL_IT: 'web_sell_it_id',
      SELL_IT: 'titip_jual_id',
      CORRECTION_MONITORING_USER: 'correction_monitoring_user_id',
      TRANSFER: 'transfer_payment_id',
      INSPECTION_HISTORY: 'inspection_history_id',
      MST_TITIP_JUAL: 'titip_jual_id',
      WEB_SETTING: 'web_setting_id',
      WEB_ARTICLE: 'article_id',
      WEB_ARTICLE_CATEGORY: 'article_category_id',
      ROLE: 'role_id',
      PAYMENT_CANCELED_HISTORY: 'payment_canceled_id',
      DEBITUR: 'debitur_id',
      AUCTION_RESULT_INVOICE_DEBITUR: 'result_auction_invoice_debitur_id',
      PPN: 'ppn_id',
      ADDITIONAL_FEES: 'additional_cost_id',
      OTHER_FEES: 'additional_cost_id',
      INVOICE_CONFIG: 'invoice_config_id',
      PUBLISH_CATALOG_LOG: 'publish_catalog_log_id',
      ADMIN_FEE_SETTING: 'admin_fee_setting_id',
      NEWS_CATEGORY: 'news_category_id',
      NEWS: 'news_id',
      CONTACT_US_ADMIN: 'contact_us_admin_id',
      CONTACT_US_USER: 'contact_us_user_id',
      DEPARTEMENT: 'departement_id',
      JOB_CAREER: 'job_career_id',
      LOCATION_AREA: 'location_area_id',
      MARITAL_STATUS: 'marital_status_id',
      RELIGION: 'religion_id',
      DEGREE: 'degree_id',
      PROVINCE: 'province_id',
      CITY: 'city_id',
      CAREER_APPLY: 'career_apply_id',
      MEMBER: 'member_id',
      TYPE_PRODUCT: 'type_product_id',
      PRODUCT: 'product_id',
      FLYER_PRODUCT: 'flayer_product_id',
      FEATURE_PRODUCT: 'feature_product_id',
      FEATURE_CHILD_PRODUCT: 'feature_child_product_id',
      GALLERY_PRODUCT: 'gallery_product_id',
      PRODUCT_360: 'product_360_id',
      VOUCHER: 'voucher_id',
      DATA_DOWNLOAD_FLYER_PRODUK: 'data_download_flayer_produk_id',
      CONSULTATION: 'consultation_id',
      MEMBER_VOUCHER: 'member_voucher_id',
      SPECIFICATION_PRODUCT: 'specification_id',
      SPECIFICATION_LABEL: 'specification_label_id',
      SPECIFICATION_VALUE: 'specification_value_id',
      PRODUCT_MODEL: 'product_model_id',
      PRODUCT_DIMENSI: 'product_dimensi_id',
      REVIEW: 'review_id',
      CAMPAIGN_PARTICIPANT: 'campaign_participant_id',
      EMAIL_EMPLOYEE: 'email_employee_id'
    }
  },
  FILE_DESCRIPTION: [
    {
      id: 1,
      name: 'Ada',
    },
    {
      id: 2,
      name: 'Tidak Ada'
    },
    {
      id: 3,
      name: 'Menyusul'
    }
  ],
  PAYMENT_METHOD: [
    { id: 1, name: 'Bank Transfer' },
    { id: 2, name: 'Debit' },
    { id: 3, name: 'Virtual Account' },
  ],
  EXCHANGES: {
    INVENTORY: 'inventory',
    INSPECTION: 'inspection-step',
    AUCTION: 'auction',
    EMAIL: 'email',
    UPDATE_INV: 'update-status-inventory',
    PRINT_CATALOG: 'exchanges-print-catalog',
    IMAGE_KTP: 'exchanges-ktp-processing',
    PUBLISH_CATALOG: 'exchanges-publish-catalog'
  },
  ACTION_TRX: {
    INSERT: 'insert',
    UPDATE: 'update',
    DEL: 'delete',
    LOG: 'log',
    LOG_REPORT: 'log-report',
    INSPECTION_STEP: 'inspection-step'
  },
  QUEUE: {
    CAR_INV: 'car-inventory',
    BIKE_INV: 'bike-inventory',
    PRINT_CATALOG: 'queue-print-catalog',
    PUBLISH_CATALOG: 'queue-publish-catalog',
    IMAGE_KTP: 'queue-ktp-processing'
  },
  ENUM: {
    Y: 'Y',
    N: 'N'
  },
  DEPOSIT_STATUS: [
    { id: 0, name: 'Batal' },
    { id: 1, name: 'Belum diverifikasi' },
    { id: 2, name: 'Terverifikasi' },
    { id: 3, name: 'Dikembalikan' },
    { id: 4, name: 'Belum Unggah Bukti Bayar' },
    { id: 5, name: 'Menunggu Pembayaran' },
    { id: 6, name: 'Menunggu Pilih Metode Pembayaran (VA)' },
  ],
  DEPOSIT_TYPE: [
    { id: 1, name: 'Online' },
    { id: 2, name: 'Offline' },
  ],
  PAYMENT_STATUS: [
    { id: 0, name: 'Batal' },
    { id: 1, name: 'Belum diverifikasi' },
    { id: 2, name: 'Terverifikasi' },
    { id: 3, name: 'Belum Unggah Bukti Bayar' },
    { id: 4, name: 'Menunggu Penyelesaian Pembayaran' },
  ],
  APP_INFO: {
    LOGO: process?.env?.LOGO_URL,
    EMAIL_CS: process?.env?.EMAIL_CS ?? 'cs.universal@lelangmobilku.co.id',
    PHONE_CS: process?.env?.PHONE_CS ?? '0811-9009404',
    WEB_INFO: process?.env?.WEB_INFO,
    ONLINE_AUCTION: process?.env?.ONLINE_AUCTION,
    WEB_SELLER: process?.env?.WEB_SELLER ?? 'https://rubysa.my.id/'
  },
  BILL_PAYMENT_METHOD: [
    { id: 1, name: 'Bank Transfer' },
    { id: 2, name: 'Debit' },
    { id: 3, name: 'Virtual Account' },
  ],

  ALLOCATION_DETAIL_STATUS: [
    { id: 1, name: 'Draft' },
    { id: 2, name: 'Ready Lelang (Akan Datang)' },
    { id: 3, name: 'Aktif Lelang' },
    { id: 4, name: 'Konfirmasi' },
    { id: 5, name: 'Tidak Terjual' },
    { id: 6, name: 'Terjual' },
    { id: 7, name: 'Batal Lelang' },
    { id: 8, name: 'Legab' }
  ],
  ALLOCATION_DETAIL_STATUS_ID: {
    DRAFT: 1,
    READY_LELANG: 2,
    AKTIF_LELANG: 3,
    KONFIRMASI: 4,
    TIDAK_TERJUAL: 5,
    TERJUAL: 6,
    BATAL_LELANG: 7,
    LEGAB: 8
  },
  ALLOCATION_LANE: {
    A: 'A',
    B: 'B',
    Z: 'Z'
  },
  OFFICIAL_ADDRESS: process.env.OFFICIAL_ADDRESS ?? 'Jl Moh Kahfi I No 24.A RT/RW 008/006 jagakarsa, jagakarsa. Jakarta selatan, kode pos 12620',
  FINANCE_REPORT_TYPES: [
    { id: 1, name: 'Deposit' },
    { id: 2, name: 'Hasil Lelang' },
    { id: 3, name: 'Riwayat Penawaran Online' },
    { id: 4, name: 'Log History' },
    { id: 5, name: 'Pelunasan Lelang' },
    { id: 6, name: 'Pengembalian Deposit' },
  ],
  HISTORY_PAYMENT_TYPE: [
    { id: 1, name: 'Deposit' },
    { id: 2, name: 'Pelunasan' }
  ],
  NIPL_STATIC_NOMINAL: {
    CAR: 5000000,
    BIKE: 1000000
  },
  WEB_ARTICLE_STATUS: [
    { id: 0, name: 'Not Publish' },
    { id: 1, name: 'Publish' },
    { id: 2, name: 'Draft' },
  ],
  LAST_DATE_EXISTING: (process.env.LAST_DATE_EXISTING || '2024-12-31').toString(),
  INVENTORY_STATUS_NAME: {
    OPERASI: 'operasi',
    TERSEDIA: 'tersedia',
    LELANG: 'lelang',
    TERJUAL: 'terjual',
    RILIS: 'rilis',
    BATAL_TITIP: 'batal titip',
    SUSPEND: 'suspend'
  },
  VEHICLE_ALLOCATION_AVALIABLE_STATUS: {
    TERSEDIA: 1,
    TIDAK_TERSEDIA: 0
  }
}
